# See https://docs.gitlab.com/ce/ci/yaml/README.html for the documentation

package:
  image: debian:10
  stage: build
  before_script:
    - apt-get update
    - apt-get install --yes python3-pip
    - pip3 install -r requirements.txt
  script:
    - ./build-documentation.sh
  artifacts:
    when: always
    paths:
      - sphinx-output.log
      - build
